name: jetleaf
description: Enterprise-grade backend framework bringing dependency injection and lifecycle management to Dart.
version: 1.2.1

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetleaf
issue_tracker: https://github.com/jetleaf/jetleaf/issues
documentation: https://jetleaf.hapnium.com/docs

topics:
  - dart-backend
  - ioc
  - dependency-injection
  - jetleaf
  - framework

keywords:
  - ioc
  - dependency-injection
  - backend-framework
  - lifecycle
  - jetleaf

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.17.0
  jetleaf_lang: ^1.1.3
  jetleaf_logging: ^1.1.3
  jetleaf_convert: ^1.1.4
  jetleaf_utils: ^1.1.3
  jetleaf_core: ^1.1.6
  jetleaf_env: ^1.1.4
  jetleaf_pod: ^1.1.5

dev_dependencies:
  test: ^1.28.0
  lints: ^6.0.0