name: jetleaf
description: A comprehensive, enterprise-grade Dart backend framework that brings Spring-like dependency injection, configuration management, and application lifecycle to Dart server-side development.
version: 1.0.0

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetleaf

topics:
- Pod
- Pod Configuration
- Pod Management
- IoC
- IoC Container

keywords:
- Pod
- Pod Configuration
- Pod Management
- IoC
- IoC Container

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.17.0
  jetleaf_lang:
    hosted: https://onepub.dev/api/fahnhnofly/
    version: ^1.0.0
  jetleaf_logging:
    hosted: https://onepub.dev/api/fahnhnofly/
    version: ^1.0.0
  jetleaf_convert:
    hosted: https://onepub.dev/api/fahnhnofly/
    version: ^1.0.0
  jetleaf_core:
    hosted: https://onepub.dev/api/fahnhnofly/
    version: ^1.0.0
  jetleaf_utils:
    hosted: https://onepub.dev/api/fahnhnofly/
    version: ^1.0.0
  jetleaf_env:
    hosted: https://onepub.dev/api/fahnhnofly/
    version: ^1.0.0
  jetleaf_pod:
    hosted: https://onepub.dev/api/fahnhnofly/
    version: ^1.0.0

dev_dependencies:
  test: ^1.21.0
  lints: ^6.0.0