jetleaf.enableautoconfiguration:
  jetleaf_data:
    - DataAutoConfiguration
    - package:jetleaf_data/data.DataAutoConfiguration
  jetleaf_security:
    - SecurityAutoConfiguration
    - package:jetleaf_security/security.SecurityAutoConfiguration
  jetleaf_web:
    - WebMvcAutoConfiguration
    - package:jetleaf_web/web.WebMvcAutoConfiguration

jetleaf.disableautoconfiguration:
  jetleaf_data:
    - DataAutoConfiguration
    - package:jetleaf_data/data.DataAutoConfiguration
  jetleaf_security:
    - SecurityAutoConfiguration
    - package:jetleaf_security/security.SecurityAutoConfiguration
  jetleaf_web:
    - WebMvcAutoConfiguration
    - package:jetleaf_web/web.WebMvcAutoConfiguration